### ISSUE TITLE
Dossier + constantes

### ISSUE THREAD

**Issue by sbazin10** [redundantautomata/french-search-engine-lite#11]
J'ai créé le dossier de notre groupe dans le repertoire commun avec le path /projet/iri/bvh, et j'y ai ajouté trois répertoires : 
- WeightFile qui contiendra les fichiers .poids générés par l'Indexer
- InvertedFileFromIndexer qui contiendra les inverted files générés par l'indexer
- InvertedFileFromMerger qui contiendra les inverted files générés par l'invertedFileMerger

Cela vous convient ?

Ensuite, je pense qu'il serait interessant de regrouper toutes les constantes (notamment  les paths vers ces différents dossiers, le path vers le corpus, et diverses autres constantes utilisés dans le programme) dans une classe dédiée, afin d'éviter d'avoir des consts qui se baladent partout comme c'est le cas actuellement, pour rendre le code un peu plus propre
J'ai déja créé la classe, j'attend votre avis avant de push.

**Comment by redundantautomata** [comment]
Parfait, habile pour le regroupement des constantes, je commençais à être perdu.

**Comment by VanheckeVincent** [comment]
Parfait.
