### ISSUE TITLE
Get weigh file recurssive

### ISSUE THREAD

**Issue by VanheckeVincent** [redundantautomata/french-search-engine-lite#3]
method getWeightFiles must be recurssive.

**Comment by VanheckeVincent** [comment]
Creation de la fonction de calcul reccursive du poid des fichiers.
Pour se faire, de nombreuses autres fonctions ont du etre reprogrammees en mode reccursif.
Le code est documente, vous trouverez sa javadoc dans le dossier doc (pour les fonctions plublique).

**Comment by redundantautomata** [comment]
Très bien, je suis entrain de la faire, mais je vais mettre mes modifications entre paranthèses et voir ce que tu as fait.

**Comment by redundantautomata** [comment]
J'ai testé tes fonctions de récursivité sur le getWeightFIles :+1: 
Sur la même arborescence de répertoires que celle du corpus du projet.
--> La structure est gardée dans le répertoire de sortie.
--> Les fichiers .poids sont à des endroits correspondant à ceux du corpus.
--> Le tf.idf (par conséquent les variables intérmediaires notamment documentFrenquency) est valide.
