### ISSUE TITLE
Est-ce que les stop-words sont correctement supprimés ?

### ISSUE THREAD

**Issue by redundantautomata** [redundantautomata/french-search-engine-lite#6]
Vérifier qu'aucun stop-word ne se trouve dans les fichiers ".poids" si (removeStopWords == true)

**Comment by redundantautomata** [comment]
Oui, c'est le cas : Checked.

**Comment by VanheckeVincent** [comment]
Il persiste beaucoup de caracteres sans aucun sens comme ... " ( < etc. De plus, les apostrophes ne sont pas presentes par defaut dans le fichier de stop word. Les 'l qu' s'... ne sont peut-etre pas retirees.
Ne devrait-on pas les considerer comme des stop-words ?

**Comment by redundantautomata** [comment]
Oui, tu as raison. De plus ces caractères spéciaux sont présents dans tellement de documents du corpus, qu'ils alourdissent considérablement nos fichiers .poids et notre fichier inverse.
Je laisse le ticket, on se concertera sur une solution demain.

**Comment by VanheckeVincent** [comment]
On cree un autre ticket pour l'ajout
