### ISSUE TITLE
Vincnent : As-tu pris en charge la méthode keepExtension ?

### ISSUE THREAD

**Issue by redundantautomata** [redundantautomata/french-search-engine-lite#7]
Lors de la sélection des fichiers à indexer dans le corpus.
Car apparemment ce n'est pas le cas, j'attends tes retours.

**Comment by VanheckeVincent** [comment]
En effet, cette methode n'est pas encore prise en compte. Ceci est mentionne dans la javadoc il me semble, ou si j'ai mal fait les choses dans de simples commentaires.

**Comment by VanheckeVincent** [comment]
Il existe un tableau d'extension de nom EXTENTION_KEEP, touts les noms de fichiers finissant par une de ses extensions sont traites. L'usage actuel permet de definir la 1er extension, mais on peut en definir plusieurs autres dans le code.

**Comment by VanheckeVincent** [comment]
Oups, autant pour moi, je libere !

**Comment by redundantautomata** [comment]
Le sujet me paraît clos.
